default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode
  timeout: 5000

development:
  <<: *default
  database: luvnotes_development

test: &test
  <<: *default
  database: luvnotes_test

production:
  <<: *default
  database: luvnotes_production

cucumber: 
  <<: *test